### ISSUE TITLE
Medication Code Review

### ISSUE THREAD

**Issue by pauljohanneskraft** [StanfordBDHG/ENGAGE-HF-Firebase#2]
### Problem

Currently, the data scheme document is still missing some medication codes and some ambiguous entries exist as well (e.g. multiple intake options for the same medication and dosage).

### Solution

We should verify that the codes are the "right" ones to use and check whether we can find codes for the remaining medications.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by pauljohanneskraft** [comment]
Do we still need this? Maybe a check of the `functions/src/data/medicationCodes.json` file?

**Comment by vishnuravi** [comment]
We can close this, thanks @pauljohanneskraft!
